version = 0.1

[default]
[default.global.parameters]
stack_name = "pager-webhooks-dev"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[prod]
[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
stack_name = "pager-webhooks-prod"
s3_prefix = "pager-webhooks-prod"
image_repositories = []
region = "us-east-2"
disable_rollback = false
resolve_image_repos = true
parameter_overrides = "Environment=prod StackName=pager-webhooks-prod MainStackName=unowned"
profile = "unowned-prod"

[dev]
[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
stack_name = "pager-webhooks-dev"
s3_prefix = "pager-webhooks-dev"
image_repositories = []
region = "us-east-2"
disable_rollback = false
resolve_image_repos = true
parameter_overrides = "Environment=dev StackName=pager-webhooks-dev MainStackName=unowned-dev DeploymentVersion=1.0.0"
profile = "unowned-prod"
